### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by luoww1992** [CLinvx/HPM-MVS_plusplus#1]
how to make dataset to test ?

**Comment by CLinvx** [comment]
Hi, the usage is almost same as MVSNet, you can use the "[colmap2mvsnet_acm.py](https://github.com/CLinvx/HPM-MVS_plusplus/blob/main/colmap2mvsnet_acm.py)" to convert COLMAP SfM result.
![image](https://github.com/CLinvx/HPM-MVS_plusplus/assets/109119609/f55894e0-6665-4bb3-880d-fcfcf597a4b6)

**Comment by luoww1992** [comment]
@CLinvx  
i use colmap from project  Vis-MVSNet, 
then run colmap2mvsnet_acm.py
then train the data, 
but i find it is slow, how to make it faster ?, my gpu is 3090

**Comment by CLinvx** [comment]
Our method is geometry-only method which requires no training. You just need to use cmake to compile the project and run the code to get the final point cloud (maybe you should change the CMakeList to ensure the code can be used in 3090, details can be found in https://github.com/GhiXu/ACMP/issues/2#issuecomment-790626051).

**Comment by luoww1992** [comment]
@CLinvx 
yes,  i see that this is  -gencode arch=compute_86,code=sm_86 in the CMakeList.txt,
but i use cuda11.3 and c++14   with VS2019 to build it,  does it have a big impact?
and i notice there are about 40000000 points, it is too large, how to reduce it  to make it faster ?

**Comment by luoww1992** [comment]
@CLinvx 
can you share a dataset about yours ?
what is your env?
 it costs how long ?

**Comment by CLinvx** [comment]
1. Different versions have little effect on algorithm performance.
2. To make it faster, there are several solutions: 1) Downsample the image resolution or set the parameters "max_image_size" (HPM.h) lower. 2) Reduce the number of mandatory consistency, you can set the parameters "geom_iterations == 2" (main.cpp). 3) You can also abandon the HPM structure, e.g., add code "max_hpm_scale = max_num_downscale;" in Line 984/1034 (main.cpp). **Note that, these changes may make the algorithm less effective.**
3. One of our datasets is Tanks and Temples dataset, the download link is https://drive.google.com/file/d/1YArOJaX9WVLJh4757uE8AEREYkgszrCo/view.
4. We conducted a runtime analysis experiment on a computer with an Intel i5-12600 CPU and an RTX 3070 GPU. The runtime of depth map generation for a 3200 × 2130 image is 54.65s.

**Comment by luoww1992** [comment]
@CLinvx , this is my ply result with horse dataset form tankandtemples by default code cmd.
i run all code in VS2019, and run .exe default cmd in cmd.
it costs me about 40mins, while it is bad result. https://drive.google.com/drive/folders/1dX5eSEjqbX25gEnFh3x68VC3yHiH6Fiv?usp=sharing

**Comment by CLinvx** [comment]
We recommend that you use image semantic segmentation as described in README to filter noise point in the sky area.

**Comment by luoww1992** [comment]
@CLinvx 
i use this data with mask to test, it looks better than before, https://drive.google.com/drive/folders/1QEvhp1ZO82nBIHz5RmxJClaCQ6gLRd3R?usp=sharing
but i have the same question, bad result. how to refine it ?

**Comment by CLinvx** [comment]
> @CLinvx i use this data with mask to test, it looks better than before, https://drive.google.com/drive/folders/1QEvhp1ZO82nBIHz5RmxJClaCQ6gLRd3R?usp=sharing but i have the same question, bad result. how to refine it ?

You can adjust the parameters according to the current situation, such as the parameters in ConfidenceEvaluation (main.cpp, L780).
![image](https://github.com/CLinvx/HPM-MVS_plusplus/assets/109119609/6e80cb93-7370-490d-a1cb-b0ab7e5f2a20)
